groups:
- name: product_catalog_test
  rules: 
  - alert: HighGCdowntime
    expr: rate(jvm_gc_pause_seconds_sum{action="end of minor GC", environment="test", application="product-catalog"}[1h]) > 0.5
    for: 5m
    annotations:
      summary: "High GC downtime on {{ $labels.instance }}"
      description: "High GC downtime on {{ $labels.instance }}"
      
  - alert: ConnectionAcquireTime
    expr: hikaricp_connections_acquire_seconds_sum{application="product-catalog", environment="test"} / hikaricp_connections_acquire_seconds_count{application="product-catalog", environment="test"} > 10
    for: 5m
    annotations:
      summary: "Connection time is too long {{ $labels.instance }}"
      description: "Connection time is too long {{ $labels.instance }}"

- name: product_catalog_demo
  rules: 
  - alert: HighGCdowntime
    expr: rate(jvm_gc_pause_seconds_sum{action="end of minor GC", environment="demo", application="product-catalog"}[1h]) > 0.5
    for: 5m
    annotations:
      summary: "High GC downtime on {{ $labels.instance }}"
      description: "High GC downtime on {{ $labels.instance }}"
      
  - alert: ConnectionAcquireTime
    expr: hikaricp_connections_acquire_seconds_sum{application="product-catalog", environment="demo"} / hikaricp_connections_acquire_seconds_count{application="product-catalog", environment="demo"} > 10
    for: 5m
    annotations:
      summary: "Connection time is too long {{ $labels.instance }}"
      description: "Connection time is too long {{ $labels.instance }}"

- name: product_catalog_stage
  rules: 
  - alert: HighGCdowntime
    expr: rate(jvm_gc_pause_seconds_sum{action="end of minor GC", environment="stage", application="product-catalog"}[1h]) > 0.5
    for: 5m
    annotations:
      summary: "High GC downtime on {{ $labels.instance }}"
      description: "High GC downtime on {{ $labels.instance }}"
      
  - alert: ConnectionAcquireTime
    expr: hikaricp_connections_acquire_seconds_sum{application="product-catalog", environment="stage"} / hikaricp_connections_acquire_seconds_count{application="product-catalog", environment="stage"} > 10
    for: 5m
    annotations:
      summary: "Connection time is too long {{ $labels.instance }}"
      description: "Connection time is too long {{ $labels.instance }}"
      
- name: product_catalog_prod
  rules: 
  - alert: HighGCdowntime
    expr: rate(jvm_gc_pause_seconds_sum{action="end of minor GC", environment="prod", application="product-catalog"}[1h]) > 0.5
    for: 5m
    annotations:
      summary: "High GC downtime on {{ $labels.instance }}"
      description: "High GC downtime on {{ $labels.instance }}"
      
  - alert: ConnectionAcquireTime
    expr: hikaricp_connections_acquire_seconds_sum{application="product-catalog", environment="prod"} / hikaricp_connections_acquire_seconds_count{application="product-catalog", environment="prod"} > 10
    for: 5m
    annotations:
      summary: "Connection time is too long {{ $labels.instance }}"
      description: "Connection time is too long {{ $labels.instance }}"