spring:
  datasource: 
    url: jdbc:mariadb://localhost:3306/customer_registration_service?connectTimeout=100
    driver-class-name: org.mariadb.jdbc.Driver
    initialize: true
    data: data-mysql.sql
    username: sa
    password: sa
 
    task:
    scheduling:
      pool:
        size: 3

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    enable:
      jvm: false
      hikaricp: false
      process: false
      logback: false
      tomcat: false
      system: false
      jdbc: false
      http: false

camunda:
  bpm:
    #    metrics:
    #      monitoringBeansXml: file:/camunda/configuration/camunda-monitoring-beans.xml
    job-execution:
      enabled: false
